//// First Exercise 

let NAME = prompt("Enter Your Name");
let AGE = prompt("Enter Your Age");

if(AGE >= "18"){
    alert("Welcome To Our Page" + NAME)
}
else{
    alert("Sorry ,You Cannot Login")
}





let Name_1 = prompt("Enter your Name");

if (  Name_1 == "Ahmed"){
    alert("The Name Are Matching");
}


let Name =prompt("enter your Name")

if (Name != "Ahmed")
{
alert ( "The Name Are Not Matching")
}


//// Done By Alghalia /////